"""Add token_updated_at field to User model

Revision ID: 3d22462b7925
Revises: 6ba9c0d7d9f3
Create Date: 2025-04-12 22:56:04.092600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d22462b7925'
down_revision = '6ba9c0d7d9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('angelone_token_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('angelone_token_updated_at')

    # ### end Alembic commands ###
