"""Add AngelOne API fields to User model

Revision ID: 6ba9c0d7d9f3
Revises: 9b3156931f6c
Create Date: 2025-04-12 22:46:39.206498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba9c0d7d9f3'
down_revision = '9b3156931f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('angelone_api_key', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('angelone_client_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('angelone_password', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('angelone_totp_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('angelone_feed_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('angelone_refresh_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('angelone_jwt_token', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('angelone_ws_configured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('angelone_ws_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('angelone_ws_enabled')
        batch_op.drop_column('angelone_ws_configured')
        batch_op.drop_column('angelone_jwt_token')
        batch_op.drop_column('angelone_refresh_token')
        batch_op.drop_column('angelone_feed_token')
        batch_op.drop_column('angelone_totp_token')
        batch_op.drop_column('angelone_password')
        batch_op.drop_column('angelone_client_code')
        batch_op.drop_column('angelone_api_key')

    # ### end Alembic commands ###
